[package]
name = "akaze"
version = "0.1.0"
authors = ["John <johnstalbaum@gmail.com>"]

[dependencies]
image = "0.20.0"
log = "0.4.5"
env_logger = "0.5.13"
rustfmt = "0.10.0"
primal = "0.2.3"
time = "0.1.40"
num_cpus = "1.8.0"
scoped_threadpool = "0.1.9"
random = "0.12.2"
